### ISSUE TITLE
Exclusion of Data

### ISSUE THREAD

**Issue by shubhaminnani** [Karenxzr/IDHmut#1]
Hi,
This is excellent work and great use-case.
As we are aware that there are around 1100 patients in GBM+LGG collection, and 879 patients have WSI  and 801 slides corresponding have IDH info available. As in the paper, it is mentioned that 379 patient data is used. Any Other Molecular criteria was used to short list this 379 slides?

Thanks in advance.

**Comment by Karenxzr** [comment]
> Hi, This is excellent work and great use-case. As we are aware that there are around 1100 patients in GBM+LGG collection, and 879 patients have WSI and 801 slides corresponding have IDH info available. As in the paper, it is mentioned that 379 patient data is used. Any Other Molecular criteria was used to short list this 379 slides?
> 
> Thanks in advance.

Hi, thanks for your question. We had 379 patients data because we downloaded IDH mutation status labels from cbioportal at 09/2020, and only patients with IDH labels were used in the study. We also excluded frozen slides only using FFPE ones. Then the final number is 379. I’m not sure if there are further updates of the dataset especially idh status labels, if yes, I guess the model performance can be further improved.
